config/routes.rb
Amigoseguidor::Application.routes.draw do
  root :to => "home#index"
    
  devise_for :users do
    get "sign_in",  :to => "devise/sessions#new"
    get "sign_out", :to => "devise/sessions#destroy"
  end
  
  namespace :user do
    root :to => "users#index"
  end

  resources :messages, :only => [:index, :show, :new, :create, :destroy]
  resources :groups
  resources :wishlists

  ## Routes to add/edit itens of a list
  get  "add_item"    => "wishlists#new_item"
  post "add_item"    => "wishlists#create_item"
  get  "edit_item"   => "wishlists#edit_item"
  post "edit_item"   => "wishlists#update_item"
  get  "remove_item" => "wishlists#destroy_item"

  ## Secret friend
  match "/secret/:id" => "groups#secret_friend"

  match "/send_invitation" => "groups#send_invitation"
  match "/new_invitation/:id" => "groups#new_invitation"

  match "/privategroup" => "groups#privategroup"
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :sender,   :foreign_key => "sender", :class_name => "User"
  belongs_to :receiver, :foreign_key => "receiver", :class_name => "User"
  belongs_to :group
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :authenticate_user!  
  before_filter :clean_up_session
  
  include FaceboxRender

  def index
    @memberships = Membership.where("user_id = ?", current_user.id).all

    if(params[:sent])
      @messages = current_user.sent_msgs.where("group_id = ?", params[:group].to_i).all #maybe add some order here
    elsif(params[:received])
      @messages = current_user.received_msgs.where("group_id = ?", params[:group].to_i).all #maybe add some order here
    end
  end

  def show
    @message = Message.find(params[:id])
    check_security(@group)
    respond_to do |format|
      format.html
      format.js { render_to_facebox }
    end
  end

  def new
    @message = Message.new
    @users = User.all

    respond_to do |format|
      format.html
      format.js { render_to_facebox }
    end
  end

  def create
    params[:message][:receiver] = User.find(params[:message][:receiver])
    @message = Message.new(params[:message])
    @message.sender = current_user
    if @message.save 
      redirect_to(@message, :notice => 'Message was successfully created.')
    else
      render :action => "new"
    end
  end

  def destroy
     @message = Message.find(params[:id])
     @message.destroy
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_messages.html.erb
<hr/>
<% if messages.empty? %>
<p>No messages</p>
<% else %>
  <table>
    <tr>
      <th> Subject </th>
    <tr>
  <% messages.each do |m| %>
    <tr>
      <td><%= link_to m.subject , message_path(m), :remote => true %><br/><td>
    <tr>
  <% end %>    
  </table>
<% end %>

app/views/messages/index.html.erb
<h1>Caixa de Mensagens</h1>
<div id="left_menu" >
  <ul>
  <li><%= link_to "Sair", user_root_path %></li>
  <li><%= link_to "Nova Mensagem", new_message_path, :remote => true %></li>
  <li>Entrada</li>
    <ul>
    <% @memberships.each do |m| %>
      <li><%= link_to m.group.name, messages_path(:received => true, :group => m.group.id), :remote => true %></li>
    <% end %>
    </ul>
  <li>Saida</li>
    <ul>
    <% @memberships.each do |m| %>
      <li><%= link_to m.group.name, messages_path(:sent => true, :group => m.group.id), :remote => true %></li>
    <% end %>
    </ul>
  </ul>
</div>

<div id="message_view">

</div>

app/views/messages/index.js.erb
$("#message_view").html("<%= escape_javascript(render :partial => 'messages', :locals => {:messages => @messages}) %>") 

app/views/messages/new.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :to %>
    <%= f.select :receiver, options_from_collection_for_select(@users, "id", "name") %>
  </div>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>De:</b>
  <%= @message.sender.name %>
</p>

<p>
  <b>Para:</b>
  <%= @message.receiver.name %>
</p>

<p>
  <b>Assunto:</b>
  <%= @message.subject %>
</p>

<p>
  <b>Mensagem:</b>
  <%= @message.body %>
</p>

<%= link_to 'Apagar', @message, :confirm => 'Certeza?', :method => :delete %>