config/routes.rb
Amigoseguidor::Application.routes.draw do
  root :to => "home#index"
    
  devise_for :users do
    get "sign_in",  :to => "devise/sessions#new"
    get "sign_out", :to => "devise/sessions#destroy"
  end
  
  namespace :user do
    root :to => "users#index"
  end

  resources :messages, :only => [:index, :show, :new, :create, :destroy]
  resources :groups
  resources :wishlists

  ## Routes to add/edit itens of a list
  get  "add_item"    => "wishlists#new_item"
  post "add_item"    => "wishlists#create_item"
  get  "edit_item"   => "wishlists#edit_item"
  post "edit_item"   => "wishlists#update_item"
  get  "remove_item" => "wishlists#destroy_item"

  ## Secret friend
  match "/secret/:id" => "groups#secret_friend"

  match "/send_invitation" => "groups#send_invitation"
  match "/new_invitation/:id" => "groups#new_invitation"

  match "/privategroup" => "groups#privategroup"
end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :name, :uniqueness => true
  validates :name, :description, :gift_price, :presence => true  
  validates :gift_price, :numericality => true
  
  has_many :memberships, :dependent => :destroy
  has_many :users, :through => :memberships

  has_many :messages

  # Save the group just created and add a new membership
  def save_with_membership(owner)
    status = self.save
    self.memberships.create(:user_id => owner.id,
                             :group_id => id, 
                             :owner => true,
                             :membership_status => 1) if status # Approved
    status
  end

  def owner
    User.find(memberships.where(:owner => true).first.user_id)
  end

  def self.search(name)
    if(name)
      where("name like ? AND private = ?", "%#{name}%", false).all
    else 
      []
    end
  end
end

app/controllers/groups_controller.rb
require 'uuid'
class GroupsController < ApplicationController
  before_filter :authenticate_user!  
  before_filter :clean_up_session
  
  def index
    @groups = Group.search(params[:search])
  end

  def show
    @group = Group.find(params[:id])
    check_security(@group)
  end

  def new
    @group = Group.new
  end

  def edit
    @group = Group.find(params[:id])
    check_security(@group)
  end

  def create
    @group = Group.new(params[:group])
    if @group.save_with_membership(current_user)
      flash[:notice] = "Grupo criado com sucesso"
      redirect_to user_root_path
    else
      redirect_to :action => 'new'
    end
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(params[:group])
      redirect_to(@group, :notice => "Grupo atualizado com sucesso")
    else
      redirect_to :action => 'edit'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    flash[:notice] = "Grupo removido"
    redirect_to user_root_path
  end

  def secret_friend
    @group = Group.find(params[:id])
    @friend = Membership.where(:group_id => params[:id], :user_id => current_user).first.friend
  end

  def new_invitation
    @group = Group.find(params[:id])
  end

  def send_invitation
    @group = Group.find(params[:group])
    ## Get the token for this invitation
    uuid = UUID.new
    token = uuid.generate
    pc = Privatecode.new
    pc.group_id = @group.id
    pc.code = token 
    GroupMailer.invite(params[:email], @group, token).deliver
    pc.save!
    flash[:notice] = "Convite enviado com sucesso"
    redirect_to group_path(@group)
  end

  def privategroup
    pcs = Privatecode.where("code like ?", params[:code]).all
    if(pcs.empty?)
      flash[:error] = "Codigo invalido"
      redirect_to groups_path
    else
      pc = pcs[0]
      g = Group.find(pc.group_id)
      Membership.new(:user_id => current_user.id, :group_id => pc.group_id).save!
      pc.destroy
      flash[:notice] = "Voce ja esta participando do grupo '#{g.name}'"
      redirect_to user_root_path
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_admin.html.erb
<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Participantes', '#' %> <br/ >

<h2> Status dos participantes </h2>

app/views/groups/_form.html.erb
<% form_for(@group) do |f| %>
    <%= f.error_messages %>
    <p>
        <%= f.label :name, 'Nome do seu grupo:' %><br />
        <%= f.text_field :name %>
    </p>
    <p>
        <%= f.label :description, 'Descrição do grupo:' %><br />
        <%= f.text_area :description %>
    </p>
    <p>
        <%= f.label :gift_price, 'Valor do presente:' %><br />
        <%= f.text_field :gift_price %>
    </p>
    <p>
        <%= f.label :revelation_day, 'Data da revelação:' %><br />
        <%= f.datetime_select :revelation_day %>
    </p>
    <p>
        <%= f.label :revelation_address, 'Local da revelação:' %><br />
        <%= f.text_field :revelation_address %>
    </p>
    <p>
        <%= f.label :revelation_address_link, "Link para o endereço ("  %>
        <%= link_to 'GMaps', 'http://maps.google.com.br',:target => "_blank" %> ) <br />
        <%= f.text_field :revelation_address_link %>
    </p>
    <p>
        <%= f.label :private, "Privado" %>
        <%= f.check_box :private %> <span>Grupos privados não aparecerão na pesquisa por grupos </span><br/>
    </p>
    <p>
        <%= f.submit 'Confirmar' %>
    </p>
<% end %>

app/views/groups/_groups.html.erb
<% unless @groups.empty? %>
  <table>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Criador</th>
      <th/>
    <tr>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.description %></td>
        <td><%= group.owner.name %></td>        
        <td><%= link_to "Participar", "#" %></td>
      <tr>
    <% end %>
  <table>
<% end %>

app/views/groups/_owner.html.erb
<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Adicionar Administradores', "#" %> |
<%= link_to 'Apagar grupo', @group, :confirm => "Tem certeza que deseja apagar este grupo?", :method => 'delete' %> |
<%= link_to 'Enviar convite', "/new_invitation/#{@group.id}" %> |
<%= link_to 'Passar a bandeira', "#" %> <br/>

<h2> Status dos participantes </h2>

Tabel com nome do participante e status corrente

app/views/groups/_participants.html.erb
Tabela com nome dos participantes e links para suas listas

app/views/groups/edit.html.erb
<h1>Editar <%= @group.name %> </h1>
<p>Find me in app/views/groups/edit.html.erb</p>
<%= render :partial => "form", :object => @group %>
<%= link_to('Back', group_path(@group)) %>

app/views/groups/index.html.erb
<h1>Grupos</h1>

<p><font color="red"><%= flash[:error] %></font></p>
<p><font color="green"><%= flash[:notice] %></font></p>

<h3>Se você recebeu um código para participar de um grupo privado, entre com seu código no espaço abaixo e clique 'Participar' <h3>

<% form_tag :controller => 'groups', :action => 'privategroup', :method => :post do %>
  <p>
    <%= text_field_tag :code, params[:code] %>
    <%= submit_tag "Participar", :name => nil %>
  </p>
<% end %>


<h3> Se você não possui um código, pode procurar por grupos públicos e enviar um pedido de ingresso para os administradores</h3>

<% form_tag groups_path, :method => :get, :remote => true do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Procurar", :name => nil %>
  </p>
<% end %>

<div id="groups" >
  <%= render :partial => 'groups' %>
</div>

<%= link_to "Voltar", user_root_path %>

app/views/groups/index.js.erb
$("#groups").html("<%= escape_javascript(render :partial => 'groups') %>")

app/views/groups/new.html.erb
<h1>Novo Grupo</h1>
<%= render :partial => "form", :object => @group %>
<%= link_to('Voltar', user_root_path) %>

app/views/groups/new_invitation.html.erb
<%= form_tag :controller => 'groups', :action => 'send_invitation', :method => :post do %>
  <p>
    <%= hidden_field_tag :group, params[:group], :value => @group.id %>
    <p> 
      Email:
      <%= text_field_tag :email, params[:email] %>
    </p>
    <%= submit_tag "Enviar convite", :name => nil %>
  </p>
<% end %>
<%= link_to "Voltar", group_path(@group) %>

app/views/groups/secret_friend.html.erb
<h2>Amigo secreto</h2>
<% if @friend %>
  <h3><b>Nome:</b> <%= @friend.name %> </h3>
  <%= link_to "Ver lista de presentes", "#" %>
<% else %>
  <h2> Vc nao tem amigo ainda! <h2>
<% end %>
<%= link_to "Voltar", group_path(@group) %>

app/views/groups/show.html.erb
<h1><%= @group.name %></h1>

<p id="notice"><%= notice %></p>

<%= link_to "Meu Amigo Secreto", "/secret/#{@group.id}" %> |
<%= link_to "Minha lista de presentes", "#" %> |
<% if current_user.owns?(@group) %>
  <%= render :partial => 'owner', :object => @group %>
<% elsif current_user.admin?(@group) %>
  <%= render :partial => 'admin', :object => @group %>
<% end %>

<p>
  <b>Descrição:</b>
  <%= @group.description %>
</p>

<%= render :partial => 'participants', :object => @group %><br /> 

<%= link_to 'Voltar', user_root_path %>