config/routes.rb
Amigoseguidor::Application.routes.draw do
  root :to => "home#index"
    
  devise_for :users do
    get "sign_in",  :to => "devise/sessions#new"
    get "sign_out", :to => "devise/sessions#destroy"
  end
  
  namespace :user do
    root :to => "users#index"
  end

  resources :messages, :only => [:index, :show, :new, :create, :destroy]
  resources :groups
  resources :wishlists

  ## Routes to add/edit itens of a list
  get  "add_item"    => "wishlists#new_item"
  post "add_item"    => "wishlists#create_item"
  get  "edit_item"   => "wishlists#edit_item"
  post "edit_item"   => "wishlists#update_item"
  get  "remove_item" => "wishlists#destroy_item"

  ## Secret friend
  match "/secret/:id" => "groups#secret_friend"

  match "/send_invitation" => "groups#send_invitation"
  match "/new_invitation/:id" => "groups#new_invitation"

  match "/privategroup" => "groups#privategroup"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
  # relationships
  
  # relationship Users X Messages
  has_many :sent_msgs,     :foreign_key => "sender", :class_name => 'Message'
  has_many :received_msgs, :foreign_key => "receiver", :class_name => 'Message'

  # relationship Users X Groups
  has_many :memberships, :dependent => :destroy
  has_many :groups, :through => :memberships 
  
  # relationship Users X Whishlists
  has_many :wishlists
  has_one :membership

  def owns?(group)
    m = memberships.where(:group_id => group.id).first
    m ? m.owner : false
  end

  def admin?(group)
    m = memberships.where(:group_id => group.id).first
    m ? m.adm : false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!  
  before_filter :clean_up_session
  def index
    @user = current_user
    @memberships = @user.memberships
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_membership.html.erb
<h2> Membership </h2>
<% @memberships.each do |membership| %>
  <%= link_to membership.group.name, group_path(membership.group_id) %>
  <br/ >
<% end %>

app/views/users/index.html.erb
<h1><%= current_user.name %></h1>

<p><font color="red"><%= flash[:error] %></font></p>
<p><font color="green"><%= flash[:notice] %></font></p>

<%= link_to "Sair", sign_out_path %> |
<%= link_to "Caixa de Mensagens", messages_path %> |
<%= link_to "Criar Grupo", new_group_path %> |
<%= link_to "Grupos", groups_path %> |
<%= link_to "Nova lista de presentes", new_wishlist_path %>

<br />
<%= render :partial => "membership" %>

<!-- TEMP CODE -->
<hr />
<h2>Listas </h2>
<% @user.wishlists.each do |l|  %>
  <%= link_to "Lists number#{l.id}", wishlist_path(l.id) %>
<% end %>