config/routes.rb
Amigoseguidor::Application.routes.draw do
  root :to => "home#index"
    
  devise_for :users do
    get "sign_in",  :to => "devise/sessions#new"
    get "sign_out", :to => "devise/sessions#destroy"
  end
  
  namespace :user do
    root :to => "users#index"
  end

  resources :messages, :only => [:index, :show, :new, :create, :destroy]
  resources :groups
  resources :wishlists

  ## Routes to add/edit itens of a list
  get  "add_item"    => "wishlists#new_item"
  post "add_item"    => "wishlists#create_item"
  get  "edit_item"   => "wishlists#edit_item"
  post "edit_item"   => "wishlists#update_item"
  get  "remove_item" => "wishlists#destroy_item"

  ## Secret friend
  match "/secret/:id" => "groups#secret_friend"

  match "/send_invitation" => "groups#send_invitation"
  match "/new_invitation/:id" => "groups#new_invitation"

  match "/privategroup" => "groups#privategroup"
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  # relationship Whishlists X User
  belongs_to :user

  # relationship Wishlists X Wishitens
  has_many :wishitems, :dependent => :destroy
  accepts_nested_attributes_for :wishitems, :allow_destroy => true
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :clean_up_session, :only => [:index, :show, :destroy]

  include FaceboxRender

  def index
    @wishlists = Wishlist.all
  end

  def show
    @wishlist = Wishlist.find(params[:id])
    check_security(@wishlist)
  end

  def new
    # save the action
    session[:last_action] ||= 'new'
    
    @itens = session[:itens]
    @wishlist = Wishlist.new
  end

  def edit
    # save the action
    session[:last_action] ||= 'edit'
    session[:last_id] ||= params[:id]

    @wishlist = Wishlist.find(params[:id])
    check_security(@wishlist)

    session[:itens] ||= @wishlist.wishitems
    @itens = session[:itens]
  end

  def create
    @wishlist = Wishlist.new(params[:wishlist])
    session[:itens].each do |wishitem| 
      @wishlist.wishitems << wishitem unless wishitem == nil
    end
    if @wishlist.save
      flash[:notice] = "Lista criada com sucesso"
      redirect_to user_root_path
    else
      render :action => 'new'
    end
  end

  def update
    @wishlist = Wishlist.find(params[:id])
    @wishlist.wishitems = session[:itens].delete_if {|i| i == nil}
    if @wishlist.update_attributes(params[:group])
      redirect_to(@wishlist, :notice => "Lista atualizada com sucesso")
    else
      redirect_to :action => 'edit'
    end
  end

  def destroy
    @wishlist = Wishlist.find(params[:id])
    @wishlist.destroy
    flash[:notice] = "Lista removida"
    redirect_to user_root_path
  end

################################################################################
##                         Itens management                                   ##
################################################################################
  def new_item
    @wishitem = Wishitem.new
    respond_to do |format|
      format.html
      format.js { render_to_facebox }
    end
  end

  def create_item

    if(params[:wishitem])
      session[:itens] ||= []
      params[:wishitem].delete(:index)
      session[:itens] << Wishitem.new(params[:wishitem])
    end

    if session[:last_action] == 'new'
      redirect_to :action => session[:last_action]
    else
      redirect_to edit_wishlist_path(session[:last_id])
    end
  end

  def edit_item
    @wishitem = session[:itens][params[:index].to_i]
    respond_to do |format|
      format.html
      format.js { render_to_facebox }
    end
  end

  def update_item

    if(params[:wishitem])
      session[:itens] ||= []
      session[:itens][params[:wishitem].delete(:index).to_i] = Wishitem.new(params[:wishitem])
    end

    if session[:last_action] == 'new'
      redirect_to :action => session[:last_action]
    else
      redirect_to edit_wishlist_path(session[:last_id])
    end
  end

  def destroy_item
    session[:itens][params[:index].to_i] = nil
  end  
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/_form.html.erb
<%= form_for(@wishlist) do |f| %>
  <%= f.hidden_field :user_id, :value => current_user.id.to_s %>

  <% if @wishlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wishlist.errors.count, "error") %> prohibited this message from being saved:</h2>
      <ul>
      <% @wishlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <h2>Itens:</h2>
    <div id="wishitens"> 
       <% if @itens %>
          <table id="wishlist">
            <tr>
               <th>Name</th>
               <th>Description<th>
               <th>URL<th>
               <th>Category<th>
               <th></th>
               <th></th>  
            </tr>
            <% @itens.each_with_index do |item,index| %>
              <% if(item) %>
                <tr id="elem_<%=index%>" >
                  <td><%= item.name %></td>
                  <td><%= item.description %></td>
                  <td><%= item.url %><td/>
                  <td><%= item.category %><td/>
                  <%= link_to "Edit",   edit_item_path(:index => index),   :remote => true %> 
                  <%= link_to "Delete", remove_item_path(:index => index), :remote => true %>    
                <tr/>
              <% end %>
            <% end %>
          </table>
       <% end %>
    </div>

    <%= link_to "Add item", add_item_path, :remote => true %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wishlists/_item.html.erb
<div id="wishitem" >
  <%= form_for :wishitem, @wishitem do |wf| %>
    <%= wf.hidden_field :index, :value => params[:index] %>    
    <p><%= wf.label :name %><br/> <%= wf.text_field :name %></p>
    <p><%= wf.label :description %> <br/> <%= wf.text_area :description %></p>
    <p><%= wf.label :url %> <br/> <%= wf.text_field :url %></p>
    <p><%= wf.label :category %> <br/> <%= wf.text_field :category %></p>
    <%= wf.submit %>
  <% end %>
</div>

app/views/wishlists/destroy_item.js.erb
$("#elem_<%= params[:index] %>").remove();

app/views/wishlists/edit.html.erb
<h1>Wishlists#edit</h1>
<p>Find me in app/views/wishlists/edit.html.erb</p>

<%= render 'form' %>
<%= link_to 'Back', user_root_path %>

app/views/wishlists/edit_item.html.erb
<%= render 'item' %>

app/views/wishlists/index.html.erb
<h1>Wishlists#index</h1>
<p>Find me in app/views/wishlists/index.html.erb</p>

<% @wishlists.each do |w| %>
  <%= w.id %> <br />
<% end %>

<%= link_to "Voltar", user_root_path %>

app/views/wishlists/new.html.erb
<h1>Wishlists#new</h1>
<p>Find me in app/views/wishlists/new.html.erb</p>

<%= render 'form' %>
<%= link_to 'Back', user_root_path %>

app/views/wishlists/new_item.html.erb
<%= render 'item' %>

app/views/wishlists/show.html.erb
<% if @wishlist.user_id == current_user.id %>
<h1>Wishlists#show</h1>
<p>Find me in app/views/wishlists/show.html.erb</p>
<h2>Itens:</h2>
    <div id="wishitens"> 
          <table id="wishlist">
            <tr>
               <th>Name</th>
               <th>Description<th>
               <th>URL<th>
               <th>Category<th>
            </tr>
            <% @wishlist.wishitems.each_with_index do |item,index| %>
              <% if(item) %>
                <tr id="elem_<%=index%>" >
                  <td><%= item.name %></td>
                  <td><%= item.description %></td>
                  <td><%= item.url %><td/>
                  <td><%= item.category %><td/>
                <tr/>
              <% end %>
            <% end %>
          </table>
    </div>

<%= link_to "Edit", edit_wishlist_path(@wishlist) %> |
<% else %>
<p>Você está tendando acessar algo que não é seu... isso é muito feio</p>
<% end %>
<%= link_to "Back", user_root_path %>